### DISCUSSION TITLE
Controlling virtual alignment of last_close_paren

### DISCUSSION THREAD

**Discussion by alonbl** [jeremiah-c-leary/vhdl-style-guide#1013] [General]
Hi,

I succeeded in reaching the following structure:

```
    process1 : process (
            x1,
            x2,
            x3,
            x4
                                 ) is
    begin
````

I would like the `) is` to be aligned with parent.

```
    process1 : process (
            x1,
            x2,
            x3,
            x4
    ) is
    begin
````

I could not find the indent statement to do so, can you please help?
It must be something to do with `last_close_paren` but I could not figure it out.

Thanks!

---

My configuration:

```
rule:
  global:
    align_else_keywords: 'no'
    align_left: 'yes'
    align_paren: 'no'
    align_when_keywords: 'yes'
    association_element: add_new_line
    association_list_comma: add_new_line
    blank_line_ends_group: false
    comment_line_ends_group: false
    compact_alignment: false
    first_open_paren: remove_new_line
    first_paren_new_line : 'no'
    indentSize: 4   # remove when indent_size works
    indent_size: 4  # does not work use indentSize but leave documented one
    last_close_paren: add_new_line
    new_line_after_assign: 'yes'
    record_constraint_close_paren: add_new_line
    record_constraint_comma: remove_new_line
    record_constraint_element: add_new_line
    record_constraint_open_paren: remove_new_line
    severity: Error
    style: no_blank_line

  process_030: 
    disable: yes
```
