### DISCUSSION TITLE
Rule group json syntax?

### DISCUSSION THREAD

**Discussion by urbite** [jeremiah-c-leary/vhdl-style-guide#1258] [General]
A customer's project requires all VHDL keywords to be capitalized. I've had to replace my SHFT keyswitch 3 times :grin:

The following in the docs regarding setting case for all keywords seems to point to the solution.
https://vhdl-style-guide.readthedocs.io/en/latest/configuring_rule_groups.html
```
rule:
  group:
     case::keyword:
       case: 'lower'
     case::label:
       case: 'upper'
     case::name:
       case: 'upper'
     length:
       disable: True
     naming:
       disable: True
```
As a json neophyte, I didn't see how to handle the rule group :: syntax in the json file.

Initially I'd like to use vsg to just uppercase all the keywords. I found an example on how to disable all rules, then attempted to add the rule group to just uppercase the keywords. Here's the resulting json file, vsg_keyworks_us.json that was created.
```
{       
  "rule":{
    "global":{
      "disable": true
    },
    "group":{
      "case": {
        "keyword" : {
          "case": 'upper'
        }
      }
    },
  }
}
```
Here's the command used to apply the rules to the target vhdl file, along with the results. Examining the file shows that no keywords were changed to uppercase.
```
vsg -c vsg_keywrd_uc.json --fix -f foo_vsg.vhd

File:  foo_vsg.vhd
================================================================================
Phase 7 of 7... Reporting
Total Rules Checked: 0
Total Violations:    0
  Error   :     0
  Warning :     0
```

Any suggestions or help is appreciated.

**Comment by urbite** [comment]
Modified the json file and also tried a yaml file (as the rule group example is in yaml).

Neither configuration reported and violations, so subsequently no changes to the vhdl file.

modified json rule file
```
{       
  "rule":{
    "global":{
      "disable": true
    },
    "group":{
      "case::keyword": {
        "case": 'upper'
      }
    },
  }
}
```

yaml rule file
```
rule:
  global:
    disable: True
  group:
     case::keyword:
       case: 'upper'
```

**Comment by urbite** [comment]
I wondered if after globally disabling everything, the keyword group needed to be enabled. 

```
rule:
  global:
    disable: True
  group:
     case::keyword:
       disable: False
       case: 'upper'
```

After setting 'disable' false, *most* of the keywords were capitalized. Some of the keywords that weren't capitalized (but were expected to be) included:
-  parameter class (**signal, variable, constant**) and direction (**in, out, inout**) in procedure parameter lists. Didn't have any functions, but assume the same would apply. Note that declarations local to the procedure (**constant**, **variable**) were capitlized.
- wait statements (**wait on**, **wait for**, **wait until**)
- conditional exit from loop (**exit when**)
- the 'in' keyword in for loops. FOR , LOOP, TO, DOWNTO are capitalized
- **null** statement
- **others** in case statement
- **others** in element mapping (e.g.  foo <= (0 => '1', others => '0')

The vhdl code that was used had an empty entity (no port list) and no component prototypes. So it's not certain if the direction parameters in port lists are capitalized with the group setting.
