### ISSUE TITLE
Have `constant_400` align keywords only at the same hierarchical level

### ISSUE THREAD

**Issue by JHertz5** [jeremiah-c-leary/vhdl-style-guide#1081]
**Is your feature request related to a problem? Please describe.**
At the moment, `constant_400` applies the same alignment to all `=>` keywords within a constant decalaration. This can cause problems if there is a hierarchy, e.g. the constant is an an array of records or an array of arrays.

For example, take the file below. The `=>` keywords next to `ENUM_1` and `ENUM_2` are aligned, and the `=>` keywords within each of the sub-arrays/records is also aligned. I would like the structure to maintain this.
```vhdl
entity test is
end entity test;

architecture rtl of test is

  constant my_constant : my_type := (
    ENUM_1 => (
      A => 1,
      B => 2,
      C => 3
    ),
    ENUM_2 => (
      A => 1,
      B => 2,
      C => 3
    )
  );

begin

end architecture rtl;
```

When I run rule `constant_400` on the code, I get the code below. In this code, all of the `=>` keywords are aligned regardless of their level in the heirarchy of the data structure.

```vhdl
entity test is
end entity test;

architecture rtl of test is

  constant my_constant : my_type := (
    ENUM_1 => (
      A    => 1,
      B    => 2,
      C    => 3
    ),
    ENUM_2 => (
      A    => 1,
      B    => 2,
      C    => 3
    )
  );

begin

end architecture rtl;
```

Note: I have disabled a few other rules to produce the result above, for the purposes of demonstration:
```yaml
rule:
  constant_012:
    disable: true
  constant_016:
    disable: true
  element_association_101:
    disable: true
  whitespace_005:
    disable: true
  whitespace_006:
    disable: true
```

**Describe the solution you'd like**
I would like `cosntant_400` to be able to handle separately align `=>` keywords at different heirarchical levels. Apologies if this is complicated!

**Comment by JHertz5** [comment]
It would be good to have the same on `sequential_400` and `concurrent_400`.

**Comment by JHertz5** [comment]
It would be good to have the same on `sequential_400` and `concurrent_400`.
With the following config
```yaml
rule:
  concurrent_012:
    first_paren_new_line: 'no'
    assign_on_single_line: 'ignore'
  sequential_009:
    first_paren_new_line: 'no'
    assign_on_single_line: 'ignore'
  variable_assignment_008:
    first_paren_new_line: 'no'
    assign_on_single_line: 'ignore'
  element_association_100:
    disable: true
  concurrent_401:
    align_left: 'yes'
    align_paren: 'no'
  sequential_402:
    align_left: 'yes'
    align_paren: 'no'
  variable_assignment_004:
    align_left: 'yes'
    align_paren: 'no'
  variable_assignment_401:
    align_left: 'yes'
    align_paren: 'no'
```

the code below:
```vhdl

entity test is
end entity test;

architecture rtl of test is

begin

  test_signal <= (
    others => (
      data         => (others => '0'),
      update_pulse => '0'
    )
  );

  proc_test : process is
  begin

    test_signal <= (
      others => (
        data         => (others => '0'),
        update_pulse => '0'
      )
    );

    test_variable := (
      others => (
        data         => (others => '0'),
        update_pulse => '0'
      )
    );

  end process proc_test;

end architecture rtl;
```

produces the following output:
```
$ ./bin/vsg -c ./test.yml -f ./test.vhd
================================================================================
File:  ./test.vhd
================================================================================
Phase 5 of 7... Reporting
Total Rules Checked: 532
Total Violations:    2
  Error   :     2
  Warning :     0
----------------------------+------------+------------+--------------------------------------
  Rule                      |  severity  |  line(s)   | Solution
----------------------------+------------+------------+--------------------------------------
  concurrent_400            | Error      |         10 | Move => 8 columns
  sequential_400            | Error      |         20 | Move => 8 columns
----------------------------+------------+------------+--------------------------------------
```
