### ISSUE TITLE
docs: Typos 

### ISSUE THREAD

**Issue by vornkat-iis** [jeremiah-c-leary/vhdl-style-guide#1143]
Some minor errors in the docs which took me some minutes to figure out:

## docs/tool_integration/pre-commit.rst
Should be (without a v in the tag) two times on that page:
```
repos:
  - repo: https://github.com/jeremiah-c-leary/vhdl-style-guide
    rev: 3.18.0
    hooks:
      - id: vsg
``` 

# docs/tool_integration/generic.rst
Should be `--all_phases` instead of `--all-phases`.

Just some nits to a tool which was great to setup and we are so far very happy to use! Thank you for providing it!
