### ISSUE TITLE
Rule for new lines between end of generic map and port map

### ISSUE THREAD

**Issue by tossegus** [jeremiah-c-leary/vhdl-style-guide#1176]
Hi!

I tried looking for rules regarding the end of the `generic map` in combination with the start of the `port map`, but couldn't find any rule that matches what I was looking for (see below).

Violation:
```
generic map (
...
)
port map (
...
);
```

Fix:
```
generic map (
...
) port map (
...
);
```

**Describe alternatives you've considered**
Locally in my project I added a number of consecutive greps to find these violations (which works well), but having the rule directly in VSG would be very much preferred 😄

**Comment by jeremiah-c-leary** [comment]
Evening @tossegus ,

I would agree there is no rule to enforce the behavior you are looking for.  The rule `instantiation_005` is close, but it will always want to put `port map` on it's own line.   I am guessing you would want `port map` to be moved to it's own line if it was on the same line as the instance declaration?

Violation
```vhdl
  U_FIFO : FIFO port map (

  U_FIFO : FIFO
     generic map (
     )
     port map (
```
Fix
```vhdl
  U_FIFO : FIFO
     port map (

  U_FIFO : FIFO
     generic map (
     ) port map (
```
If so I could add to configuration options with the following defaults:
```yaml
rules:
   instantiation_005:
       after__instantiation:  "new line"
       after_generic_map: "new line"
```
This would match the current behavior.  Then for your formatting the configuration would be:
```yaml
rules:
   instantiation_005:
       after_instantiation:  "new line"
       after_generic_map: "no new line"
```
Would that update give you the desired formatting?

--Jeremy
