### ISSUE TITLE
How to enforce snail_case for Function/Procedure arguments?

### ISSUE THREAD

**Issue by obruendl** [jeremiah-c-leary/vhdl-style-guide#1249]
Is it possible to enforce snail_case for VC procedure arguments? I configured them for "case: lower" - but this does not report errors if I name an argument in camelCase (starting lower-case but containing upper-case letters).

**Comment by JHertz5** [comment]
Hi @obruendl. 

Lowercase should allow for snail_case. Are you asking for the tool to enforce that there are underscores between words? That is may be much more difficult.

With regards to the problem that you described, could you please provide example code and configuration to demonstrate your problem? This will make it easier to reproduce your problem and investigate.

**Comment by JHertz5** [comment]
Hi @obruendl. I've put something together on [this branch](https://github.com/JHertz5/vhdl-style-guide/tree/issue-1251). Feel free to give it a try and let me know whether it works for you. The branch currently works for function and procedure declarations, and for procedure calls, but not for function calls. This is because VSG's parser does not currently recognise function calls, so it will be a fair bit of work to get that implemented. I'll have a go, but it will take some time.

**Comment by JHertz5** [comment]
In the meantime, I noticed that your config lists case rules individually and sets them all to `lower`. I don't know if you're aware already, but in case you're not, you can use 
```yaml
rule:
  group:
    case:
      case: "lower"
```
to set all case rules (including future rules that haven't been added yet) to be lowercase. This means that you can have a smaller config file and don't have to update it to include new case rules. Just a suggestion.

**Comment by JHertz5** [comment]
FYI, I've raised a PR, #1251, to address this issue.

**Comment by obruendl** [comment]
@JHertz5 

I tried to simplify the ./lint/config/vsg_config_overlay_vc.yml file as you suggested:

```
rule:
    group:
        case:
            case: lower
    architecture_025:
        names: ["a"]
    constant_600:
        disable: true
    function_017:
        case: lower
        case_exceptions: []
    generic_600:
        disable: true
    length_002:
        disable: true # Better long VC files than many short ones
    variable_004:
        case: lower
        suffix_exceptions: []
    variable_600:
        disable: true
   ```
   
However, with this file VSG complains about many snail_case identifiers in the related code. To me it looks like this is not working correctly - at least if I use it as an overlay to a base config (./lint/config/vsg_config.yml) which defines all the rules separately.

Let me know my modification to the file is not matching what you suggested. Ohterwise, I guess this would be a new issue, right?
