### ISSUE TITLE
Lower/upper case rules.

### ISSUE THREAD

**Issue by m-kru** [jeremiah-c-leary/vhdl-style-guide#255]
As an example take rule `constant_004 (This rule checks the constant name is lower case)`. Now imagine that I want the opposite, the constant name must be upper case. There is no such rule. There are 2 possible options:

1.  I can add new rule `constant_015 (This rule checks the constant name is upper case)`, but to enable this rule I need to set 2 options in config file to maintain backward compatibility (rule `constant_004` is enabled by default):
```
    # Disable constants to be lower case
    constant_004:
        disable: true
    # Force constants to be upper case
    constant_015:
        disable: false
```
One solution is to have such rules disabled by default, then to configure the case, user would have to set only one option in config file (no overhead). However this breaks backward compatibility (I do not know if you care about this), as rule `constant_004` is enabled by default.

2. Add case parameter to the rule `constant_004`. Then only one option would need to be set in config file, and it would maintain backward compatibility (lower case by default):
```
    # Force constants to be upper case
    constant_004:
        case: upper
```

What do you think? Which solution do you prefer? Or maybe you have better idea?

**Comment by jeremiah-c-leary** [comment]
Hey m-kru,

I think the second option would be preferred.  It keeps backwards compatibility and gives the user the option to change the case to their preference.  I could also keep the configuration file smaller.

Let's say you wanted everything uppercased except the process keyword (process_004) and the architecture keyword (architecture_004).  I believe the following configuration would work:

```yaml
---
rule:
  global:
    case: upper
  process_004:
    case: lower
  architecture_004:
    case: lower
...
```

As VSG is configuring the rules, if an attribute does not exist it should just ignore it.  This would allow users to minimize the number of rules to configure.

There are probably a handful of rules that would need to be updated in vsg/rules:

   lower_case_rule.py
   lowercase_word_after_colon_rule.py
   lowercase_word_rule.py
   uppercase_end_label.py
   uppercase_word_rule.py

These could be updated with the case attribute and default to the appropriate case.  I think this would cover all the case checking rules to handle both lower and upper case.  We could probably refactor lowercase_word_rule.py and uppercase_word_rule.py into a single rule.

I really like this idea.

Thank  you.
