### ISSUE TITLE
singal_008 for other keywords

### ISSUE THREAD

**Issue by mdennis070** [jeremiah-c-leary/vhdl-style-guide#269]
signal_008 allows for a prefix to be enforced for signal names. This feature request would add this ability for generic, constant, type, subtype, variable, and component names

**Comment by jeremiah-c-leary** [comment]
I agree, this would be a good idea.

**Comment by m-kru** [comment]
I am working on this. Will create PR soon.

**Comment by m-kru** [comment]
@jeremiah-c-leary I have encountered one issue, that we have already faced today :).

With this configuration:
```
rule:
    global:
        disable: true
    generic_020:
       prefixes: ['G__']
    signal_008:
        prefixes: ['s_']
```
 No checks are executed, what is not compliant with documentation that says: 

> Note: Prefixes are disabled by default. To enable prefixes, set the prefixes attribute on the rule.

To enable these checks I need to enable them explicitly:
```
rule:
    global:
        disable: true
    generic_020:
        disable: false
        prefixes: ['G__']
    signal_008:
        disable: false
        prefixes: ['s_']
```

It can be fixed in 2 ways.

1. The first one is to make them behave like is said in the documentation.
2. The second one is to treat all prefix rules like all other rules, they need to be enabled explicitly.

I prefer the second option, plus we provide some default prefixes like `G_` for generic, `s_` for signals, `v_` for variables and `C_` for constants.
