### ISSUE TITLE
Disabling rules for files in certain folders

### ISSUE THREAD

**Issue by imd1** [jeremiah-c-leary/vhdl-style-guide#580]
I have a number of folders (e.g.`sim`) that contain files where I wish to disable a rule in those files, i.e. a rule that is globally enabled.

Is there a mechanism other than place code tags at the start of each file in the sim folders?

**Comment by jeremiah-c-leary** [comment]
You could use a configuration file like this:
```yaml:
rule:
  comment_011:
     disable:  True
file_list:
  - $PATH_TO_DIRECTORY/*.vhd
  - $TOP_LEVEL_DIRECTORY/verification/sim/*.vhd
```
and call it with the `-c` option:
```mono
$ vsg -c vsg.yaml
```
You can even put exceptions based on the file:
```yaml:
rule:
  comment_011:
     disable:  True
file_list:
  - $PATH_TO_DIRECTORY/*.vhd
     rule:
        comment_011:
           disable: False
  - $TOP_LEVEL_DIRECTORY/verification/sim/*.vhd
```
Multiple configurations are also supported so you can layer rule configurations.

I place a configuration file in every directory that has source code I want to operate on so I just have to call the configuration.

**Comment by imd1** [comment]
> You could use a configuration file like this:
> 
> ```
> rule:
>   comment_011:
>      disable:  True
> file_list:
>   - $PATH_TO_DIRECTORY/*.vhd
>   - $TOP_LEVEL_DIRECTORY/verification/sim/*.vhd
> ```
> 
> and call it with the `-c` option:
> 
> ```
> $ vsg -c vsg.yaml
> ```
> 
> You can even put exceptions based on the file:
> 
> ```
> rule:
>   comment_011:
>      disable:  True
> file_list:
>   - $PATH_TO_DIRECTORY/*.vhd
>      rule:
>         comment_011:
>            disable: False
>   - $TOP_LEVEL_DIRECTORY/verification/sim/*.vhd
> ```
> 
> Multiple configurations are also supported so you can layer rule configurations.
> 
> I place a configuration file in every directory that has source code I want to operate on so I just have to call the configuration.

Thanks for the answer...a few follow on questions spring to mind...
1. Can the file list contain regular expressions which would allow specification of all `sim` folders at whatever position in the folder hierarchy?
2. Is the file list relative or full path? If relative, relative to what?

**Comment by jeremiah-c-leary** [comment]
> Can the file list contain regular expressions which would allow specification of all sim folders at whatever position in the folder hierarchy?

I use `glob` from the Python standard library:  https://docs.python.org/3/library/glob.html.

It looks like it supports the `**` option to traverse trees.

> Is the file list relative or full path? If relative, relative to what?

It is relative to where VSG is called.  I use an environment variable to indicate the projects top level directory.

If you wanted to apply a configuration to every `sim` directory you could try this:

```yaml
rule:
   comment_011:
       disable: True
file_list:
   - $PROJECT_DIR/**/sim/*.vhd
```

**Comment by imd1** [comment]
Thanks....I will try your suggestions and let you know how I get on...

**Comment by imd1** [comment]
Sorry but I'm not getting anywhere with file_list: in a config file. Please could you point me towards a concrete set of examples to try and get working.

**Comment by jeremiah-c-leary** [comment]
I tried using the tree `**`, but it did not seem to work.
I have this working at the base directory of vsg:
```yaml
  1 file_list:
  2   - vsg/tests/styles/jcl/*.vhd
```

**Comment by jeremiah-c-leary** [comment]
I ran into a small issue with the `**`.  I need to make it recursive.  Then I ran into another small problem.

**Comment by jeremiah-c-leary** [comment]
I just pushed a fix.  let me know if it is working now.

**Comment by imd1** [comment]
I wonder whether it's something else.

I pass a "list" of files to VSG on the command line. Is there a compatibility issue with the use of `file_list` in a config file?

**Comment by jeremiah-c-leary** [comment]
Are you doing something like this:
```mono
$ vsg -f vsg/**/exit_statement/*.vhd vsg/**/wait_statement/*.vhd vsg/tests/constant/rule_001_test_input.vhd -of summary
File: vsg/tests/exit_statement/rule_300_test_input.fixed.vhd ERROR (87 rules checked) [Error: 2] [Warning: 0]
File: vsg/tests/exit_statement/rule_300_test_input.vhd ERROR (87 rules checked) [Error: 2] [Warning: 0]
File: vsg/**/wait_statement/*.vhd ERROR (87 rules checked) [Error: 1] [Warning: 0]
File: vsg/tests/constant/rule_001_test_input.vhd ERROR (87 rules checked) [Error: 2] [Warning: 0]
```

**Comment by imd1** [comment]
> Are you doing something like this:
> 
> ```
> $ vsg -f vsg/**/exit_statement/*.vhd vsg/**/wait_statement/*.vhd vsg/tests/constant/rule_001_test_input.vhd -of summary
> File: vsg/tests/exit_statement/rule_300_test_input.fixed.vhd ERROR (87 rules checked) [Error: 2] [Warning: 0]
> File: vsg/tests/exit_statement/rule_300_test_input.vhd ERROR (87 rules checked) [Error: 2] [Warning: 0]
> File: vsg/**/wait_statement/*.vhd ERROR (87 rules checked) [Error: 1] [Warning: 0]
> File: vsg/tests/constant/rule_001_test_input.vhd ERROR (87 rules checked) [Error: 2] [Warning: 0]
> ```

Sort of yes, multiple  specific files with no use of * or **

**Comment by jeremiah-c-leary** [comment]
Hey @imd1 ,

I just pushed a possible fix for this to branch issue-580.  Could you check it out.

Thanks,

--Jeremy

**Comment by imd1** [comment]
I am currently trying out the possible fix on branch issue-580.

When I install VSG, I always run the unit tests, and they are currently failing on this branch - so FYI

**Comment by imd1** [comment]
Still having problems with a simple example....

I supply a list of files to VSG with a global config file

I have created a new config file `file_config.yml` as follows, and I supply it to VSG as an extra config file

```
file_list:
    - /path/to/file/with/port_025/disabled/module1_tb.vhd
        rule:
            port_025:
                disable: True

```

The idea is that port_025 is enabled in the global config file, and I want to disable this rule for the file indicated, and this in one of the files supplied to VSG to process

When I run, I get the following error:

```
ERROR: Invalid configuration file: /path/to/file_config.yml
mapping values are not allowed here
  in "/path/to/file_config.yml", line 3, column 13

```

**Comment by jeremiah-c-leary** [comment]
Try adding a colon to the end of the file name:
```yaml
file_list:
    - /path/to/file/with/port_025/disabled/module1_tb.vhd:
        rule:
            port_025:
                disable: True
```
