### ISSUE TITLE
Enable/Disable "groups" of rules

### ISSUE THREAD

**Issue by nfrancque** [jeremiah-c-leary/vhdl-style-guide#651]
**Is your feature request related to a problem? Please describe.**
I'm not sure exactly how this would be implemented, but I have found myself having to fiddle with the rule configuration after major updates to set up new / modified rules to be the same as what seem to be very similar rules.  For example, we ignore the rules that require a newline before and after the procedure/process/function signature.  Right now this ends up being ~5-10 different rules.  It'd be nice if this could be a single switch, without having to use a different "style" file.

**Describe the solution you'd like**
As a user, I think I would like to be able to do something like this:

```yaml
rule_group_blank_line_after:
  disable: true
rule_group_blank_line_before:
  disable: true
rule_group_align:
  comment_line_ends_group: false
```

**Describe alternatives you've considered**
The current alternative is basically to figure out what these rule groups are and disable each individually.  This works fine it just takes a bit to figure out.  I may be wrong about the `comment_line_ends_group` feature, please let me know if a similar ability already exists to enable/disable settings like that and `blank_line_ends_group` etc for all rules that implement it.
