### ISSUE TITLE
concurrent_003 and procedure_call_400

### ISSUE THREAD

**Issue by timkoers** [jeremiah-c-leary/vhdl-style-guide#791]
I can't align the concurrent statements and procedure calls like this:

```
begin
  (
    test     => '1',
    test_two => '2',
  )
```

or 

```
begin
  testproc
  (
    test     => '1',
    test_two => '2',
  )
```
I'd like to align to the parantesis, but with an extra indent, or the option below

```
begin
  testproc (
    test     => '1',
    test_two => '2',
  )
```

**Comment by jeremiah-c-leary** [comment]
Hey @timkoers,

The rule `concurrent_003` would not be applied in your examples as they are not concurrent signal assignments.

As for formatting of the procedure call...if you ran into the following example:
```vhd
testproc(test =>
'1', test_two
=> '2')
```
How would you want it formatted?

**Comment by timkoers** [comment]
> The rule concurrent_003 would not be applied in your examples as they are not concurrent signal assignments.
That is correct, however, the same structure is used for concurrent assignments.

The example above could be formatted in two ways, but since statement already contains a new line, I'd keep both sides of the operand (=>) on the same line

**Comment by jeremiah-c-leary** [comment]
Hey @timkoers,

Could you post a version of my example into your preferred format?  It helps me understand what you are looking for and then I use the examples in my tests to ensure the formatting is correct.

--Jeremy

**Comment by timkoers** [comment]
Sure!

```
testproc (
  test     =>'1', 
  test_two => '2'
)
```

And
```
(
  test,
  test_two,
) := test_three;
```

**Comment by jeremiah-c-leary** [comment]
Hey @timkoers,

I have pushed an  update for this to the issue-791 branch.  Currently only `concurrent_procedure_call`s are being checked and fixed.  When you get a chance could you run the latest on the branch and let me know if there are any issues?

In my tests I used the following configuration options:
```yaml
rule:
  procedure_call_003:
    first_open_paren : 'remove_new_line'
    last_close_paren : 'add_new_line'
    association_list_comma : 'remove_new_line'
    association_element : 'add_new_line'
  procedure_call_400:
    align_left : 'yes'
    align_paren : 'no
```
 to match the following format:
```vhdl
testproc (
  test     => '1', 
  test_two => '2'
);
```


Thanks,

--Jeremy
