### ISSUE TITLE
Potential rule conflict

### ISSUE THREAD

**Issue by birdybro** [jeremiah-c-leary/vhdl-style-guide#795]
**Environment**
Windows 11, Visual Studio Code, VSG version 3.11.0 (latest release as of submitting bug report) using default configuration.

**Describe the bug**
When a case statement is nested inside an if-then statement, the formatter applies far too many newlines and is very inefficiently reformatting the code.

**To Reproduce**
1. Get this file --> https://github.com/MiSTer-devel/SMS_MiSTer/blob/abc889b070122961a550ede47e2be37f175c67cc/rtl/system.vhd
2. Format it with VSG
3. Check the changes to the case statements nested within the if-then statements.

**Expected behavior**
I would expect the case statements to not have an extra newline after each assignment operator and semicolon.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/16388068/177653620-7b66765c-e0f9-4156-8039-d5d50804cbbf.png)

After:
![image](https://user-images.githubusercontent.com/16388068/177653635-c2ab370c-ec78-4a43-af03-43001edc6451.png)

Expected output:
![image](https://user-images.githubusercontent.com/16388068/177653655-29856925-712e-4c73-9215-cdeaf9051d7d.png)

Other expected output:
![image](https://user-images.githubusercontent.com/16388068/177653782-33ef7ee2-339b-4420-b568-f238c54ece18.png)

**Comment by jeremiah-c-leary** [comment]
Hey @birdybro,

The blank lines around the case statements are configurable.  Try the following configuration YAML file:
```yaml
rule:
  # These rule configurations will vertically compact case_statements
  case_007:
    style: "no_blank_line"
  case_009:
    style: "no_blank_line"
  case_010:
    style: "no_blank_line"
  case_200:
    style: "no_blank_line"
  case_201:
    style: "no_blank_line"
  # This rule configuration will align all the port declaration colons in the entity declaration
  entity_017:
    blank_line_ends_group: false
    comment_line_ends_group: false
  # This rule configuration will align all the => in port maps in instantiations
  instantiation_010:
    blank_line_ends_group: false
    comment_line_ends_group: false
```
I also added in `entity_017` and `instantiation_010` to show you other possible rule configurations.

You can use the above configuration using the following command:
```mono
$ vsg -c config.yaml -f system.vhd --fix
```

There is a [section](https://vhdl-style-guide.readthedocs.io/en/latest/configuring.html) in the documentation that covers the various configuration options.

Let me know if that configuration gives you the formatting you are looking for.

Regards,

--Jeremy
