### ISSUE TITLE
library_009 and comment_010 overlap

### ISSUE THREAD

**Issue by Scafir** [jeremiah-c-leary/vhdl-style-guide#883]
**Environment**
 CentOS Linux 7 (Core)
VHDL Style Guide (VSG) version: 3.13.1+zip.file

**Describe the bug**
`library_009` and `comment_010` are checking the same lines of code. If one sets a different indentation level for `library_009` it is then impossible to pass successfully style checking, as one of the two rules is guaranteed to fail

**To Reproduce**
1. Use `rules.yaml`:
```
rule:
  library_008:
    indentSize: 0
  library_009:
    indentSize: 0
```
`sample.vhd`:
```
library ieee;
  --! For logic elements
use ieee.std_logic_1164.all;
--! For using natural type
use ieee.numeric_std.all;
```
3. Run `vsg -c rules.yaml -f sample.vhd`
4. See that both `library_009` and `comment_010` are triggered

**Expected behavior**
Two possible solutions:
* `comment_010` should not check lines that are already checked by `library_009`, or
* `library_009` should be removed and `comment_010` respect indent level of `library_008`

**Comment by jeremiah-c-leary** [comment]
Evening @Scafir ,

It took a bit, but I believe I have a solution for this.  I added `use_clause` to the indent configuration and added a special option `token_after_library_clause` which can be used to configure the indenting of `use_clause`s.

If you use the following configuration, you will get the indenting you want:
```yaml
   indent:
    tokens:
      use_clause:
        keyword:
          token_after_library_clause: current
```
There is [indent documentation](https://github.com/jeremiah-c-leary/vhdl-style-guide/blob/issue-883/docs/configuring_indentation.rst) which describes how VSG sets indents.

Let me know if this fixes the issue for you.

Regards,

--Jeremy
