### ISSUE TITLE
Multiline Indent Rules: behaviour when first_paren_new_line

### ISSUE THREAD

**Issue by Scafir** [jeremiah-c-leary/vhdl-style-guide#901]
**Environment**
Fedora 37, VHDL Style Guide (VSG) version: 3.14.0+zip.file

**Describe the bug**
It does not seem to be possible to obtain the following:
```
wr_data <= (
  0,
  65535,
  32768
);
```

**To Reproduce**
Let's take `concurrent_401` as an example.
Following documentation we get the following rules:
```
# sampleRules.yaml
rule:
  concurrent_012:
    first_paren_new_line: no
  concurrent_401:
    disable: False
    align_left: True
    align_paren: False
```
With the following sample:
```
architecture rtl of my_entity is

begin

  wr_data <= (
    0,
    65535,
    32768
  );

end architecture rtl;
```
We obtain:
```
architecture rtl of my_entity is

begin

  wr_data <= (
  0,
  65535,
  32768
  );

end architecture rtl;
```

**Expected behavior**
The content of the array should be one indentation further than the parent indentation.

**Comment by jeremiah-c-leary** [comment]
Hey @Scafir ,

I was looking at your configuration and if you change it to this:
```yaml
# sampleRules.yaml
rule:
  concurrent_012:
    first_paren_new_line: 'no'
  concurrent_401:
    disable: False
    align_left: 'yes'
    align_paren: 'no'
```
It should give you the correct indent.

--Jeremy
